deployment.made-by-comkom.de:
  host: deployment.made-by-comkom.de
  stage: staging
  branch: master
  user: p702307
  identityFile: ~
  http_user: p702307
  deploy_path: /home/www/p702307/html/deploytest/staging