oze-essen.webseiten.cc:
  host: oze-essen.webseiten.cc
  stage: staging
  branch: dev
  user: ssh-869196-5058106
  identityFile: ~
  http_user: ssh-869196-5058106
  deploy_path: /www/213585_70794/rp-hosting/5058106/6058106/typo3cms/oze_essen_2023