hosts:
  staging:
    hostname: stage-startsmart.made-by-comkom.de
    branch: dev
    remote_user: p615504
    identityFile: ~
    http_user: p615504
    deploy_path: /home/www/p615504/html/stage-startsmart

  production:
    hostname: live-startsmart.made-by-comkom.de
    branch: master
    remote_user: p615504
    identityFile: ~
    http_user: p615504
    deploy_path: /home/www/p615504/html/live-startsmart
