hosts:
  staging:
    hostname: deployment.made-by-comkom.de
    branch: master
    remote_user: p702307
    identityFile: ~
    http_user: p702307
    deploy_path: /home/www/p702307/html/deploytest/staging