<?php

/*************************************************************************
 * Extension Manager/Repository config file for ext: "project_configuration/"
 *
 * Auto generated by Extension Builder 2018-08-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 *************************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Project Configuration',
    'description' => '',
    'category' => 'misc',
    'author' => 'Team COMKOM°',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
